//
// Generated file, do not edit! Created by opp_msgtool 6.3 from MyMessage.msg.
//

#ifndef __MYMESSAGE_M_H
#define __MYMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MyMessage;
/**
 * Class generated from <tt>MyMessage.msg:6</tt> by opp_msgtool.
 * <pre>
 * message MyMessage
 * {
 *     int hopCount = 0;   // Incremented by each router that handles the packet
 *     int ttl = 15;       // Time To Live: packet is dropped when this reaches 0
 * }
 * </pre>
 */
class MyMessage : public ::omnetpp::cMessage
{
  protected:
    int hopCount = 0;
    int ttl = 15;

  private:
    void copy(const MyMessage& other);

  protected:
    bool operator==(const MyMessage&) = delete;

  public:
    MyMessage(const char *name=nullptr, short kind=0);
    MyMessage(const MyMessage& other);
    virtual ~MyMessage();
    MyMessage& operator=(const MyMessage& other);
    virtual MyMessage *dup() const override {return new MyMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getTtl() const;
    virtual void setTtl(int ttl);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline MyMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<MyMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MYMESSAGE_M_H

